var eventMap = {
  "1970": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1971": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1972": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1973": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1974": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1975": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1976": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "(1976-1990) Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1977": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1978": {
    "North America": "",
    "Central America & Caribbean": "(1978 - 1990) Nicaragua - Civil War and US Contra Activity",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1979": {
    "North America": "",
    "Central America & Caribbean": "(1979-1991) El Salvador - Civil War and Duarte Presidency",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1980": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "(1980-1992) Peru - Heightened violent activity from The Shining Path",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1981": {
    "North America": "",
    "Central America & Caribbean": "(1981-1982) Guatemala City - Insurgency and coup d'etat",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1982": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1983": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1984": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1985": {
    "North America": "Canada - Air India Flight 182 blown up mid-flight",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1986": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1987": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1988": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "Phillippines - Insurgency/Guerrilla action",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": "Ouvéa, New Caledonia - Ouvéa cave hostage taking in Caledonia Independence attack against France"
  },
  "1989": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "Sri Lanka - JVP insurrection movement against the Bandaranaike Government",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Niger - UTA Flight 772 bombing",
    "Australasia Oceania": ""
  },
  "1990": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "Pakistan - Increased violence from Sunni and Shia Muslims and Islamist insurgent groups",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1991": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1992": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "Phillippines/Myanmar - Isurgency Guerilla action",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1993": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1994": {
    "North America": "Mexico - Zapatista Uprising and Chiapas Conflict",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1995": {
    "North America": "Oklahoma City car bombing ? Mexico - Zapatista Uprising and Chiapas Conflict",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwanda Genocide",
    "Australasia Oceania": ""
  },
  "1996": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1997": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "(1997-1998) Colombia - Rebel activity from the FARC and NLA peak",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Peak of Algerian Civil War",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1998": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1999": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2000": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2001": {
    "North America": "New York, USA - 9/11 bombings",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2002": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2003": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2004": {
    "North America": "",
    "Central America & Caribbean": "Chameleceon, Honduras - 28 killed in bus shooting",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2005": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2006": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2007": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2008": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Congo - Christmas Massacres, over 400 killed",
    "Australasia Oceania": ""
  },
  "2009": {
    "North America": "Killeen, Texas - Fort Hood Shootings",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "Urumqi, China - Urumqi Riots",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2010": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2011": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Mogadishu, Somalia - 100 killed 2011 Mogadishu Truck bombing",
    "Australasia Oceania": ""
  },
  "2012": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2013": {
    "North America": "Boston, MA - Boston Marathon Bombing",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Nigeria - Boko Haram presence escalates",
    "Australasia Oceania": ""
  },
  "2014": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "China - Attack at Kunming railway station",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Various - Boko Haram expands to Chad, Niger, Cameroon",
    "Australasia Oceania": ""
  },
  "2015": {
    "North America": "San Bernardino, CA - San Bernardino Shootings",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "China - Uighur terrorism attacks",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Various - Boko Haram expands to Chad, Niger, Cameroon",
    "Australasia Oceania": ""
  }
}
