var eventMap = {
  "1970": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1971": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1972": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "Northern Ireland - Bloody Sunday and Bloody Friday",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1973": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1974": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "Greece - TWA Flight 841 bombing",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1975": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1976": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1977": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1978": {
    "North America": "",
    "Central America & Caribbean": "Nicaragua - Civil War and US Contra Activity",
    "South America": "Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1979": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1980": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "Italy - Bologna Massacre",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1981": {
    "North America": "",
    "Central America & Caribbean": "Guatemala - Insurgency and coup d'etat | El Salvador - Civil War and Duarte Presidency",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1982": {
    "North America": "",
    "Central America & Caribbean": "Guatemala - Insurgency and coup d'etat | El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1983": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1984": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "Sri Lanka - Manul Aru Massacres",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1985": {
    "North America": "Canada - Air India Flight 182 blown up mid-flight",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "Greece - EgyptAir Flight 648 Hijacking",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1986": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1987": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1988": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "Phillippines - Insurgency/Guerrilla action",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "Scotland - 270 Die in Pan Am Flight 103 Explosion",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": "Ouvea, New Caledonia - Ouvea cave hostage taking in Caledonia Independence attack against France"
  },
  "1989": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "Sri Lanka - JVP insurrection movement against the Bandaranaike Government",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Niger - UTA Flight 772 bombing",
    "Australasia Oceania": ""
  },
  "1990": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Peru - Heightened violent activity from The Shining Path | Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "Pakistan - Increased violence from Sunni and Shia Muslims and Islamist insurgent groups",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1991": {
    "North America": "",
    "Central America & Caribbean": "El Salvador - Civil War and Duarte Presidency | Nicaragua - Civil War and US Contra Activity",
    "South America": "Colombia - Expansion of heroine/cocaine cartels and guerilla activity",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1992": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "Phillippines/Myanmar - Isurgency Guerilla action",
    "South Asia": "",
    "Central Asia": "Azerbaijan - Khojaly Genocide by Armenian forces",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1993": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwandan Civil War",
    "Australasia Oceania": ""
  },
  "1994": {
    "North America": "Mexico - Zapatista Uprising and Chiapas Conflict",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "Rwanda - Rwanda Genocide",
    "Australasia Oceania": ""
  },
  "1995": {
    "North America": "Oklahoma City car bombing | Mexico - Zapatista Uprising and Chiapas Conflict",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "Japan - Sarin gas attack on Tokyo subway kills 12",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1996": {
    "North America": "Mexico - Zapatista Uprising and Chiapas Conflict",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "China - Peak of violence in Tibet from indepedence fighters",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1997": {
    "North America": "Mexico - Zapatista Uprising and Chiapas Conflict",
    "Central America & Caribbean": "",
    "South America": "Colombia - Rebel activity from the FARC and NLA peak",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Peak of Algerian Civil War",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1998": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "Colombia - Rebel activity from the FARC and NLA peak",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "United Kingdom - Lockerbie bombing of Pan Am flight 103 over Scotland kills 270",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "1999": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2000": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2001": {
    "North America": "New York, USA - 9/11 bombings",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2002": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2003": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2004": {
    "North America": "",
    "Central America & Caribbean": "Chameleceon, Honduras - 28 killed in bus shooting",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "Philippines - Superferry bombing in Manila by Islamic group kills 116.",
    "South Asia": "Nepal - Communist rebel attack against army barracks kills hundreds",
    "Central Asia": "",
    "Western Europe": "Spain - Madrid Train Bombings",
    "Eastern Europe": "Beslan, Russia - Beslan School Siege",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2005": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2006": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2007": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2008": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "Congo - Christmas Massacres, over 400 killed",
    "Australasia Oceania": ""
  },
  "2009": {
    "North America": "Killeen, Texas - Fort Hood Shootings",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "Urumqi, China - Urumqi Riots",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2010": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Peak of violence under US occupation",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2011": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "Norway - 2011 Norway attacks",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Continuation of extensive violence and official departure of US troops",
    "Sub Saharan Africa": "Mogadishu, Somalia - 100 killed 2011 Mogadishu Truck bombing",
    "Australasia Oceania": ""
  },
  "2012": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "Parachinar, Pakistan - Suicide bombing against Shi'a Muslims",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq - Continued violence",
    "Sub Saharan Africa": "",
    "Australasia Oceania": ""
  },
  "2013": {
    "North America": "Boston, MA - Boston Marathon Bombing",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "",
    "Southeast Asia": "",
    "South Asia": "",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq and Syria - Violence from ISIS engulfs the region",
    "Sub Saharan Africa": "Nigeria - Boko Haram presence escalates",
    "Australasia Oceania": ""
  },
  "2014": {
    "North America": "",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "China - Attack at Kunming railway station",
    "Southeast Asia": "",
    "South Asia": "North Waziristan, Pakistan - Operations by Pakistan against TTP and IMU forces",
    "Central Asia": "",
    "Western Europe": "",
    "Eastern Europe": "Ukraine - Missile destroys Malaysia Airlines plane over rural Ukrainian village",
    "Middle East / North Africa": "Iraq and Syria - Violence from ISIS engulfs the region",
    "Sub Saharan Africa": "Various - Boko Haram expands to Chad, Niger, Cameroon",
    "Australasia Oceania": ""
  },
  "2015": {
    "North America": "San Bernardino, CA - San Bernardino Shootings",
    "Central America & Caribbean": "",
    "South America": "",
    "East Asia": "China - Uighur terrorism attacks",
    "Southeast Asia": "",
    "South Asia": "Afghanistan - Taliban infighting",
    "Central Asia": "",
    "Western Europe": "France - 2015 Paris Attacks",
    "Eastern Europe": "",
    "Middle East / North Africa": "Iraq and Syria - Violence from ISIS engulfs the region",
    "Sub Saharan Africa": "Various - Boko Haram expands to Chad, Niger, Cameroon",
    "Australasia Oceania": ""
  }
}
